[package]
name = "rust_order_book_practice"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "3.0", features = ["derive"] }
rust_decimal = { version = "1.37.1", features = ["macros"] }
num-traits = "0.2.19"
chrono = "0.4.40"
